# Generated by Django 2.2.7 on 2019-11-14 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieshelf', '0002_moviedirector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dir_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movieshelf.MovieDirector', to_field='name')),
                ('movie_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movieshelf.MovieGenre', to_field='genre')),
            ],
        ),
    ]
